# Version information used on all builds
PRODUCT_BUILD_PROP_OVERRIDES += BUILD_DISPLAY_ID=LMY47D BUILD_ID=LMY47D BUILD_VERSION_TAGS=release-keys BUILD_UTC_DATE=0

# Versioning System
PRODUCT_VERSION_MAJOR = 5
PRODUCT_VERSION_MINOR = 1

KOS_VERSION := KOS$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(KOS_BUILD)-$(shell date -u +%Y%m%d)

PRODUCT_PROPERTY_OVERRIDES += \
  ro.kos.version=$(KOS_VERSION) \
  ro.modversion=$(KOS_VERSION)
